steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/mini-shop", "."]

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  pool:
    name: "projects/lastbit-prj-d-project-epsilon/locations/us-east1/workerPools/wp-934509345"

images:
  - gcr.io/$PROJECT_ID/mini-shop
